market_analysis_task:
  description: >
    Analyze {company}'s market position in {market}.
    Focus on understanding market needs, competitive landscape, and growth opportunities
    for {target_segment}.
  expected_output: >
    A detailed market analysis report including competitor insights, market trends,
    and actionable growth recommendations.
  agent: market_researcher

content_strategy_task:
  description: >
    Create marketing strategy for {company} to achieve {goal}.
    Develop comprehensive marketing approach targeting {market}.
  expected_output: >
    A comprehensive marketing strategy document with campaign frameworks,
    content plans, and channel recommendations for {target_segment}.
  agent: content_strategist

sales_optimization_task:
  description: >
    Develop sales strategy for {company} focused on {market}.
    Create sales optimization plan aligned with company goals.
  expected_output: >
    **Complete Sales Optimization Plan for {company}**

    A comprehensive marketing strategy document with:
    - Detailed implementation plan for {goal}
    - Targeted marketing approaches for {target_segment}
    - Tactical recommendations for business growth
  agent: sales_strategist