market_analysis_task:
  description: >
    Conduct comprehensive market research for PaycheckManager.com
    Focus on:
    - Identifying growth opportunities in the small business payroll market
    - Analyzing customer acquisition strategies
    - Understanding key pain points for small business owners
  expected_output: >
    A detailed market research report including:
    - Comprehensive analysis of small business payroll market
    - Competitor landscape assessment
    - Identification of unmet customer needs
    - Potential marketing and product positioning strategies
  agent: market_researcher

content_strategy_task:
  description: >
    Develop a targeted marketing strategy for PaycheckManager.com
    Objectives:
    - Create a compelling marketing narrative
    - Design customer acquisition approaches
    - Develop content marketing and partnership strategies
  expected_output: >
    A comprehensive marketing strategy document with:
    - Detailed marketing campaign frameworks
    - Content marketing plan
    - Partnership and distribution channel recommendations
    - Tactical approach to reducing customer acquisition costs
  agent: content_strategist
