market_analysis_task:
  description: >
    Conduct comprehensive market research for {company}
    Specific focus on:
    - Understanding {target_market}
    - Addressing {primary_challenge}
    - Identifying opportunities for {growth_goal}
  expected_output: >
    A detailed market research report including:
    - Deep dive into {target_market} characteristics
    - Strategic approach to {primary_challenge}
    - Actionable insights for {growth_goal}
    - Competitive landscape analysis
  agent: market_researcher

content_strategy_task:
  description: >
    Create a targeted marketing strategy for {company}
    Key objectives:
    - Leverage {key_differentiator}
    - Address {primary_challenge}
    - Drive {growth_goal}
  expected_output: >
    A comprehensive marketing strategy document with:
    - Positioning strategy highlighting {key_differentiator}
    - Targeted marketing approaches for {target_market}
    - Tactical plan to overcome {primary_challenge}
    - Roadmap for achieving {growth_goal}
  agent: content_strategist
  
# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
