market_analysis_task:
  description: "Analyze PaycheckManager.com's market position"
  expected_output: "Detailed market analysis report"
  agent: "market_researcher"
  context: >
    Research target market needs, analyze competitors, and identify growth opportunities.
    Focus on small business segment with 1-50 employees.

content_strategy_task:
  description: "Create marketing strategy for PaycheckManager.com"
  expected_output: "Comprehensive marketing strategy document"
  agent: "content_strategist"
  context: >
    Develop value proposition messaging, content plan, and acquisition channels
    based on market research findings.

sales_optimization_task:
  description: "Develop sales strategy for PaycheckManager.com"
  expected_output: "Sales optimization plan"
  agent: "sales_strategist"
  context: >
    Create sales funnel optimization plan and conversion tactics
    aligned with marketing strategy.